### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [ryu2400/mod_0_skills#1]
**Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub**

- [x] Did you name and structure your directories and files correctly?
- [x] Did you make one initial commit?
- [x] Did you push your initial commit to Github?

**Part II: Top Down Design**

- [x] Did you break down larger processes into multiple smaller layers?
- [ ] Did you add and commit your changes with a properly formatted commit message?
`Need to have a commit message with a verb and then a noun`
- [x] Did you push your changes to Github?

**Part III: Classes in a System** 

- [x] Did you structure and name your directories and files correctly?
- [x] Did you correctly categorize attributes and methods for each class?
- [x] Did you correctly identify data types of attributes for each class?
- [ ] Did you add and commit each set of changes separately with a properly formatted commit message?
`Need to have a commit message with a verb and then a noun and have one commit message for each class`
- [x] Did you push your changes to Github?

**Assessment Results**
- [ ] Pass
- [x] Conditional pass
- [ ] Fail with recommend for Mod 0 repeat

`Good job on this Nathan! I'd like you to redo Part 3 with more robust commit messages, and I want you to pay attention to the assessment instructions on how many commit messages we are looking for. Send your updated results to Rachel and I when you complete this!`
